server:
  port: 9090
zzp:
  name: 123
  age: 19
  height: 170cm

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootBD?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: snowfly262406
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboottest1.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql